name: Build WeChat Tweak with Theos Docker

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-tweak:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Theos Docker Container
        run: |
          # 拉取 Theos Docker 镜像（包含 ldid、Theos 等所有依赖）
          docker pull theosdev/mlnd:latest
          # 运行容器，挂载当前代码到容器内的 /tmp/src 目录，执行构建命令
          docker run --rm -v $PWD:/tmp/src -w /tmp/src theosdev/mlnd:latest \
            make -j$(nproc)

      - name: Archive DEB
        uses: actions/upload-artifact@v4
        with:
          name: wechat-tweak-deb
          path: ./packages/*.deb
