name: Build WeChat Tweak

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-tweak:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git make clang dpkg
          wget https://github.com/ProcursusTeam/ldid/releases/latest/download/ldid_linux_x86_64
          chmod +x ldid_linux_x86_64
          sudo mv ldid_linux_x86_64 /usr/local/bin/ldid

      - name: Set up Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos
          echo "THEOS=~/theos" >> $GITHUB_ENV
          echo "PATH=~/theos/bin:$PATH" >> $GITHUB_ENV

      - name: Set up Theos Linux toolchain
        run: |
          TOOLCHAIN_DIR=~/theos/toolchain/linux/iphone
          mkdir -p $TOOLCHAIN_DIR
          wget https://github.com/theos/toolchain/releases/download/2023.09.10/linux-toolchain.tar.xz -O /tmp/linux-toolchain.tar.xz
          tar -xf /tmp/linux-toolchain.tar.xz -C $TOOLCHAIN_DIR --strip-components=1
          rm /tmp/linux-toolchain.tar.xz

      - name: Download iOS SDK
        run: |
          mkdir -p ~/theos/sdks
          wget https://github.com/theos/sdks/archive/refs/heads/master.zip -O ~/theos/sdks/sdks.zip
          unzip ~/theos/sdks/sdks.zip -d ~/theos/sdks/
          cp -r ~/theos/sdks/sdks-master/* ~/theos/sdks/
          rm -rf ~/theos/sdks/sdks.zip ~/theos/sdks/sdks-master

      - name: Build Tweak
        run: |
          cd ./
          make -j$(nproc)

      - name: Archive DEB
        uses: actions/upload-artifact@v4
        with:
          name: wechat-tweak-deb
          path: ./packages/*.deb
