name: Build WeChat Tweak

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-tweak:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git make clang dpkg
          wget https://github.com/ProcursusTeam/ldid/releases/latest/download/ldid_linux_x86_64
          chmod +x ldid_linux_x86_64
          sudo mv ldid_linux_x86_64 /usr/local/bin/ldid

      - name: Set up Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos
          echo "THEOS=~/theos" >> $GITHUB_ENV
          echo "PATH=~/theos/bin:$PATH" >> $GITHUB_ENV

      - name: Download iOS SDK
        run: |
          mkdir -p ~/theos/sdks
          wget -O ~/theos/sdks/iPhoneOS13.5.sdk.tar.gz https://github.com/theos/sdks/releases/download/13.5/iPhoneOS13.5.sdk.tar.gz
          tar -xzf ~/theos/sdks/iPhoneOS13.5.sdk.tar.gz -C ~/theos/sdks
          rm ~/theos/sdks/iPhoneOS13.5.sdk.tar.gz

      - name: Build Tweak
        run: |
          cd ./
          make -j$(nproc)

      - name: Archive DEB
        uses: actions/upload-artifact@v4
        with:
          name: wechat-tweak-deb
          path: ./packages/*.deb
