name: Build WeChat Tweak

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          submodules: true

      - name: Check cache
        run: |
          echo upstream_heads=`git ls-remote https://github.com/LexusLs300h/theos.git | head -n 1 | cut -f 1`-`git ls-remote https://github.com/LexusLs300h/sdks | head -n 1 | cut -f 1` >> $GITHUB_ENV
      - name: Use cache
        id: cache
        uses: actions/cache@v4.2.1
        with:
          path: ${{ github.workspace }}/theos
          key: ${{ runner.os }}-${{ env.upstream_heads }}

      - name: Prepare theos
        uses: LexusLs300h/theos-action@main
      - name: Build Tweak
        run: |
          # 指定Theos路径
          export THEOS="/Users/runner/work/WeChatRedEnvelop/WeChatRedEnvelop/theos"
          # 执行构建打包
          make package

      - name: Archive DEB
        uses: actions/upload-artifact@v4
        with:
          name: wechat-tweak-deb
          path: ./packages/*.deb
