name: Debian Package CI

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: amd64
            platform: linux/amd64
          - arch: arm64
            platform: linux/arm64

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Debian package
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: ${{ matrix.platform }}
        outputs: type=local,dest=./build
        tags: ${{ env.PACKAGE_NAME }}:build
        build-args: |
          PACKAGE_VERSION=${{ env.VERSION }}

    - name: Test package installation
      run: |
        sudo dpkg -i build/*.deb
        sudo dpkg -r ${{ env.PACKAGE_NAME }}

    - name: Upload to GitHub Releases
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/*.deb
          build/*.changes
        draft: false
        prerelease: false

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: deb-package-${{ matrix.arch }}
        path: build/*.deb
        retention-days: 30
