name: Build WeChat Tweak

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-tweak:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos
          echo "THEOS=~/theos" >> $GITHUB_ENV
          echo "PATH=~/theos/bin:$PATH" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          sudo apt-get update
          # 安装编译 ldid 的依赖
          sudo apt-get install -y git make clang
          # 克隆 ldid 源码并编译安装
          git clone https://github.com/DHowett/ldid.git
          cd ldid
          git submodule update --init
          make
          sudo make install
          # 安装 dpkg
          sudo apt-get install -y dpkg

      - name: Build Tweak
        run: |
          cd ./
          make -j$(nproc)

      - name: Archive DEB
        uses: actions/upload-artifact@v4
        with:
          name: wechat-tweak-deb
          path: ./packages/*.deb
