name: Build Debian Package

on:
  push:
    tags:
      - 'v*'
  release:
    types: [published]
  workflow_dispatch:

env:
  PACKAGE_NAME: "your-package-name"
  VERSION: ${{ github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [amd64, arm64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up environment
      run: |
        # 移除 'v' 前缀（如果存在）
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "PACKAGE_NAME=myapp" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          devscripts \
          debhelper \
          dh-make \
          build-essential \
          fakeroot \
          lintian

    - name: Create Debian packaging structure
      run: |
        # 创建基本的 Debian 包结构
        dh_make --createorig --yes --single --packagename ${PACKAGE_NAME}_${VERSION}

    - name: Copy custom Debian files
      run: |
        cp -r debian/* ${PACKAGE_NAME}-${VERSION}/debian/

    - name: Build package
      run: |
        cd ${PACKAGE_NAME}-${VERSION}
        dpkg-buildpackage -us -uc -b

    - name: Check package with Lintian
      run: |
        lintian ${PACKAGE_NAME}_${VERSION}_*.deb

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PACKAGE_NAME }}-${{ env.VERSION }}-${{ matrix.architecture }}
        path: |
          *.deb
          *.changes
          *.buildinfo
