name: Build WeChat Tweak

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-tweak:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew update
          brew install make git

      # 添加清理Theos目录的步骤
      - name: Clean existing Theos dir
        run: rm -rf ${{ github.workspace }}/theos

      - name: Prepare Theos
        uses: huami1314/theos-action@main

      - name: Build Tweak
        run: |
          make package

      - name: Archive DEB
        uses: actions/upload-artifact@v4
        with:
          name: wechat-tweak-deb
          path: ./packages/*.deb
