name: Build WeChat Tweak

on:
  push:
    branches: [ main, master ]
  pull_request:
    branchess: [ main, master ]

jobs:
  build-tweak:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew update
          brew install make git ldid xz # 确保依赖安装完整
          # 确保Xcode命令行工具正确配置
          sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: Clean existing Theos directory
        run: |
          # 清理可能存在的Theos目录，解决目录冲突问题
          if [ -d "$HOME/theos" ]; then
            rm -rf "$HOME/theos"
          fi

      - name: Prepare Theos
        uses: huami1314/theos-action@main
        with:
          # 修正参数错误，使用支持的参数代替theos-version
          theos-src: https://github.com/theos/theos.git
          theos-sdks: https://github.com/theos/sdks.git

      - name: Build Tweak
        run: |
          export THEOS=$HOME/theos # 确保Theos路径正确
          make package

      - name: Archive DEB
        uses: actions/upload-artifact@v4
        with:
          name: wechat-tweak-deb
          path: ./packages/*.deb

